### ISSUE TITLE
Merge animations in most samples, add sample using multiple animations correctly

### ISSUE THREAD

**Issue by reduz** [KhronosGroup/glTF-Sample-Models#108]
I'm incredibly disappointed, I implemented 100% of the spec in Godot. Spent 4 days on it. At the time I'm done, I realize that, unlike what it proposes through the whole spec, glTF **does not** support multiple animations. 

Guys, It's 2017 and all DCCs support editing animation clips, so it should be perfectly possible to export all character animations in a single file without relying on cheap tricks like segmenting a timeline or having to export animations with the whole scene again in a separate file.

In the spec, the term **animations**, plural, is used through the whole thing. It totally makes sense, any animation works on a number of channels. By reading the spec it becomes obvious that multiple animations can be stored in the format.

Yet, when I go try the demos.. every demo I find uses an animation for a different node. For example on this demo:

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxAnimated

To get the animation to look like in the gif, you have to play all animations together.
In this other demo:

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan

Each bone has an animation of it's own. you must play all animations together in order to see the guy walking.

So, please change the spec to make it very clear to implementers that, in 2017, a new format does not support multiple animations. Please also urgently add an official extension to support REAL multiple animations, so this format can be used for 21st century workflows.

**Comment by reduz** [comment]
A proposed extension could be: "KHR_animations_are_actually_in_fact_separate_animations"

**Comment by reduz** [comment]
realized this should not go here.. closing.

**Comment by donmccurdy** [comment]
Actually IMO this can be kept open — we should definitely update our sample models to not use separate animations for each node, and add some new examples that have multiple distinct animations (the spec does support this).

**Comment by reduz** [comment]
Alright, reopening. Please let me know when this is updated, so can actually test this function properly in Godot. Thanks!

**Comment by javagl** [comment]
The acutal spec-related part is now discussed in https://github.com/KhronosGroup/glTF/issues/1052 

This issue here is **only** about creating more sample models showing different animation capabilities. (Maybe the title should be changed accordingly)

**Comment by reduz** [comment]
@javagl This is not about showing different animation capabilities. If the spec is to be trusted about multiple animation support, then every single demo here is wrong. If the demos are right, then the spec is wrong and multiple animation support does not match reality.

My criticism is that if you make a spec, you must follow it and use it as intended for the official demo content. 

If you want to do weird stuff lke showing a gif with an animation, then provide a .gltf with each track exported as a single animation (for reasons that honestly don't make any sense, and rendering it unusable as demo), it can't be avoided that people like me, that implements the whole specification and expects to see a regular animation playing when opening a demo, finds intense frustration to find out the official demos don't obey the spec in a practical way.

There is simply no excuse for the CesiumMan demo exporting every bone track as a different animation, it lacks any practical use.

**Comment by donmccurdy** [comment]
Here is the list of fixes I would recommend for this issue.

Some of the sample models — specifically the simple tests — are fine as they are, and would also be fine if the animations were merged. It doesn't really matter, as long as we still have some tests for multiple animations.

- AnimatedCube
- AnimatedMorphCube
- AnimatedMorphSphere
- AnimatedTriangle
- BoxAnimated
- RiggedSimple
- VC

Some of the sample models are, as @reduz points out, not following best practice by having multiple animations, even though they are technically not incorrect according to the spec.

- [ ] CesiumMan(has 19 animations, should have 1)
- [ ] CesiumMilkTruck (has 2 animations, should have 1)
- [ ] RiggedFigure (has 19 animations, should have 1)
- [ ] BrainStem (has 19 animations, should have 1)
- [ ] WalkingLady (has 10 animations, should have 1)
- [ ] Monster (has 32 animations, should have 1)

Because these are official samples, we should strive to show best practice. This is important for viewers — in [my own](https://gltf-viewer.donmccurdy.com/), I automatically play all animations, because that was necessary to make these samples animate correctly. But in a real asset, a model might need distinct animations like `run`, `walk`, `dance`, and if you play them all at the same time it will look bad, and users will get a bad result. In order to encourage viewers to do the right thing (either play the first animation only, or let the user choose one), we should try to merge the animations of those last 6 models.

Additionally, I suggest we add at least one sample model that really does need and use multiple animations. `Polly` might be a good choice.

**Comment by javagl** [comment]
@reduz At the risk of sounding naive or insistive (or both) :

> If the spec is to be trusted about multiple animation support, then every single demo here is wrong. If the demos are right, then the spec is wrong and multiple animation support does not match reality.

At which point is either the spec or any sample model "wrong" or even "inconsistent"? The BoxAnimated shows two animations. You could also merge it into one `animation` with two `animation.channel` objects - that's up to the exporter. 

But maybe the key issue here is that the animations in *this* example are *intended* to be played simulataneously - that's part of the (unfortunately unspecificied) playback behavior. So...

@donmccurdy  

> But in a real asset, a model might need distinct animations like run, walk, dance, and if you play them all at the same time it will look bad,

this may be in fact the point that this issue (or the ambiguities that @reduz criticized) was all about. That should or could explicitly addressed, and the comment at https://github.com/KhronosGroup/glTF/issues/1052#issuecomment-320262513 is certainly a first step here. 

In any case, even **if** the models are updated to all use one `animation` with multiple `channel` objects, there should still be at least *one* sample model that actually shows *multiple* animations. And (as usual), I think it should not (only) be Polly, but a triangle that is once moved and once rotated. 

(This, in fact, would be an example of two animations that could be played separately **or** combined...)

**Comment by donmccurdy** [comment]
> At which point is either the spec or any sample model "wrong" or even "inconsistent"? The BoxAnimated shows two animations.

Yes, the BoxAnimated model is very subjective, and there is no right/wrong there. The Monster model is less so — there currently 32 animations that must be played in parallel to make the monster walk, and none of those animations are meaningful on their own. If the monster had an "attack" animation too, that should not be another 32 animations, because then the viewer cannot meaningfully figure out which are grouped. The distinction between animations and channels is how we imply those actions/groups, so we should be sure to use it as such.

Put another way, unless the author has done something to imply multiple actions (such as creating separate Actions in Blender) all channels should be put into a single animation. As a result, viewers will be able to make good assumptions about how to handle playback for their needs.

> In any case, even if the models are updated to all use one animation with multiple channel objects, there should still be at least one sample model that actually shows multiple animations. And (as usual), I think it should not (only) be Polly, but a triangle that is once moved and once rotated.

Agreed!

**Comment by reduz** [comment]
@javafl to avoid getting in the extremes, one could say the spec is very misleading if implementers consider the current samples as the way animations need to be exported. As mentioned in the posts above, several of them split the tracks of a single animation into multiple animations for no practical reason at all. Saying that this is done as example that multiple animations are possible is counterproductive. Better samples should be made for this.

**Comment by scurest** [comment]
In the meantime, [here](https://gist.github.com/scurest/262731b8dcbc37b088986dfe5215861c)'s a quick script to merge multiple non-overlapping animations into one animation. It seems to work for eg. CesiumMan and Monster.

Call it like `gltf_merge_anim.py in.gltf out.gltf`.
