### ISSUE TITLE
Box.glb sets up uniforms that are never used.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glTF-Sample-Models#13]
I've seen this on other models as well but Box.glb sets up the uniforms "u_shininess" and "u_specular" while they are never actually used. When you lookup these uniforms in the fragment program you won't find them. Not the end of the world but it would be nice if the sample models were nice and clean.

It would also be nice if the JSON was laid out in expected parse order for super high performance parsing. The DOM-style JSON parser used for KhronosGroup/Vulkan-Samples is already faster than rapidjson but it is even faster if the JSON is laid out in the order it is parsed.

**Comment by javagl** [comment]
That's something that I also noticed a while ago, but didn't consider it to be an issue. Now I just *started* looking at this, and the link to https://github.com/KhronosGroup/glTF/issues/121 from [`commonProfileShaders.cpp`, line 854](https://github.com/KhronosGroup/COLLADA2GLTF/blob/5cbbe4674c16aa05cc613d8b7c50f4557b5af611/shaders/commonProfileShaders.cpp#L854) at least seems to be relevant here (maybe it saves others a few minutes of searching - even though those who dare trying to fix this issue already knew where to look for it)

Regarding the second point (that might have to be moved into a separate issue) : Maybe I misunderstood this, but doesn't this only apply to "SAX"-like parsers? I mean, every DOM-style parser will read the input from top to bottom and build the DOM anyhow, so I don't see why it should be advantageous to have the order of top-level elements be `scene`,`node`,`mesh` in contrast to the (alphabetical) `mesh`,`node`,`scene` that is used now.

**Comment by mre4ce** [comment]
https://github.com/KhronosGroup/Vulkan-Samples/blob/master/external/include/utils/json.h

Note that the ARM performance numbers are out of date.

**Comment by javagl** [comment]
(I had seen the header, but did not yet work through the documentation and benchmark setups that are explained there. From a quick glance, I did not see a comparison that was related to the "parse order" in any way (which, as I said, does not seem to make sense for a DOM parser), but I'll have to review this more thoroughly)

Regarding the unused uniforms: I added some debug statements and went through the sample models. Here is a (hopefully complete) list of the sample models and their unused uniforms:

    Loading /BrainStem/glTF/BrainStem.gltf
    Unused: technique0 u_ambient
    Unused: technique0 u_specular
    Loading /BoxWithoutIndices/glTF/BoxWithoutIndices.gltf
    Unused: technique0 u_shininess
    Unused: technique0 u_specular
    Loading /BoxTextured/glTF/BoxTextured.gltf
    Unused: technique0 u_shininess
    Unused: technique0 u_specular
    Loading /BoxSemantics/glTF/BoxSemantics.gltf
    Unused: technique0 u_shininess
    Unused: technique0 u_specular
    Loading /BoxAnimated/glTF/BoxAnimated.gltf
    Unused: technique0 u_light0Color
    Loading /Box/glTF/Box.gltf
    Unused: technique0 u_shininess
    Unused: technique0 u_specular
    Loading /2CylinderEngine/glTF/2CylinderEngine.gltf
    Loading /VC/glTF/VC.gltf
    Loading /RiggedSimple/glTF/RiggedSimple.gltf
    Unused: technique0 u_ambient
    Unused: technique0 u_shininess
    Unused: technique0 u_specular
    Loading /RiggedFigure/glTF/RiggedFigure.gltf
    Unused: technique0 u_ambient
    Unused: technique0 u_shininess
    Unused: technique0 u_specular
    Loading /ReciprocatingSaw/glTF/ReciprocatingSaw.gltf
    Loading /Monster/glTF/Monster.gltf
    Unused: technique0 u_ambient
    Unused: technique0 u_shininess
    Unused: technique0 u_specular
    Loading /GearboxAssy/glTF/GearboxAssy.gltf
    Loading /Duck/glTF/Duck.gltf
    Unused: technique0 u_ambient
    Loading /CesiumMilkTruck/glTF/CesiumMilkTruck.gltf
    Unused: technique1 u_shininess
    Unused: technique1 u_specular
    Unused: technique0 u_shininess
    Unused: technique0 u_specular
    Loading /CesiumMan/glTF/CesiumMan.gltf
    Unused: technique0 u_ambient
    Unused: technique0 u_shininess
    Unused: technique0 u_specular
    Loading /Buggy/glTF/Buggy.gltf

(If no "unused" ones are listed, then everything is fine). Again, I think that all this depends on the [`commonProfileShaders.cpp`](https://github.com/KhronosGroup/COLLADA2GLTF/blob/5cbbe4674c16aa05cc613d8b7c50f4557b5af611/shaders/commonProfileShaders.cpp#L854), so might in fact rather be an issue of COLLADA2GLTF (and not directly of the sample models). 

(BTW: I think that the `commonProfileShaders.cpp` is already rather complex, with several classes and deep nesting - it could benefit from some cleanups and refactoring, IMHO...)

(BTW2: Here are two issues: The unused uniforms, and the JSON order. You also opened https://github.com/KhronosGroup/glTF-Sample-Models/issues/15 , which also mentions *two* issues, namely the uniforms and the wrong extensions. It would be nice if each issue only contained one issue. Otherwise, it is not clear *when* one issue can be closed)

**Comment by mre4ce** [comment]
I agree, there is no guarantee and no requirement that object members are accessed in order, and it "should not" matter for a DOM-style JSON implementation. I get the argument that it should not matter so why bother, but that does not mean it's a good idea to just throw things in at random. I'm also pointing out that for very high performance parsing (beyond rapidjson) it is convenient if the JSON is layed out in parse order. Our FBX2glTF converter lays out everything in order for that reason. It's also a lot nicer to read the JSON that way.

Thanks for checking all the models for unused uniforms! I'm sure the unused uniforms is either a source or converter issue. However, now it's a sample model issue. It's bad practice to leave unused uniforms in the shaders.

Sorry, my bad, I'll open separate issues going forward. I was just going through the sample models to make sure our loader is fast, efficient and has no bugs and I ended up opening an issue with the "problems" I ran into per model. The JSON layout is also not really a sample model issue and should go back to the glTF spec. Maybe say something about preferred order.

**Comment by javagl** [comment]
The point about the performance and parse order was the following: When you load the JSON with a DOM-style parser (and, to my understanding, with *any* DOM-style parser), then it will basically read the input file, "byte by byte", from the beginning to the end, and build some internal data structures for it - that is, the DOM. And since it does not have any knowledge about the *meaning* of the data elements, there is no such thing like a "parse order". When it finds a `{` then "any" object starts, and when it finds a `}` then "any" object ends. 

(If you are talking about a specific loader that *"knows"* what glTF is, and builds glTF-specific data structures, then this might be a different story. But as far as I know, basically all JSON parsers read anything that they encounter, and store it as something that is equivalent to some deeply nested untyped(!) maps)

Now, where a performance difference *might* occur is when these internal data structures (that is, the maps that represent the DOM) are then *interpreted* in any way. There, something like a "parse order" exists, in the sense that a glTF loader will first look up stuff in the `scenes` map, then in the `nodes` map, and then in the `meshes` map. Probably. But another loader could first load all the `buffers`, or all the `images` - you never know....

Even if there is some parse order that is "more likely" than another, I doubt that this could have noticable performance differences. The only performance difference could be related to some sort of caching, but this would be so highly specific for the target loader/OS/machine that I can't imagine how to draw any general conclusions from that. 

However, I still have to digest the Json_t documentation, maybe I'm embarassingly overlooking something here.

**Comment by mre4ce** [comment]
Since we are having this discussion here now anyway.

glTF incorrectly uses JSON:

As opposed to using arrays with elements with a name property, glTF uses objects with arbitrarily named members. Normally JSON objects are well-defined with well-defined member names. As a result, a JSON parser is needed that cannot just lookup object members by name, but can also iterate over the object members as if they are array elements. Not all JSON parsers support this.

glTF has no JSON ordering requirements:

There are no requirements for how the JSON data is ordered. There are obvious benefits from ordering the JSON data, such that all references are backwards. In other words, any part of the JSON can only reference previously defined parts. This would not only make it trivial to use a SAX-style JSON parser but would also make it trivial to parse the JSON in-place manually. This can be easily up to two times faster than the fastest DOM-style parser.

There is also no required ordering of the node hierarchy. If the node hierarchy is stored depth or breath first per sub-tree (or in reverse) then it is trivial to linearly walk the hierarchy and transform the nodes from local space to global space. Recursively walking the hierarchy means random access which is not efficient. An application can sort the nodes at load time but that is just another step that could be avoided.

**Comment by emackey** [comment]
This is a glTF 1.0 bug.  It was fixed in 2.0.
