### ISSUE TITLE
Add glTF 1.1 models from the upcoming glTF tutorial

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Sample-Models#16]
@javagl for the models in https://github.com/javagl/gltfTutorialModels, do you prefer:
* That we just link to that repo from here, or
* That you open a PR to move all those models into this repo and then perhaps add an appendix to the tutorial with a list of the models and direct links to each?

**Comment by javagl** [comment]
I don't have a strong preference here. Conceptually, they are a bit different than the other models, because they are small, hand-crafted, feature-based examples, and some of them use a mixed structure (with embedded buffers but external shaders) for easier presentation in the tutorial. 

If they are moved to the official sample models repo, then they could
- either appear as "Test cases/models" in a dedicated list
- or be added to the list of existing models, possibly sorted by topic (e.g. the  "SimpleAnimation" before "Box Animated", the "SimpleSkin" before "Rigged Simple" etc.)

In any case, I agree to what you mentioned in the second point: It could be useful to link from the tutorial to the models. Either via a list in an appendix, or inlined: *"Here is an example ... it can be downloaded from the sample models repo at (link)"*. Similarly, one could add a link to the README of the models: *"SimpleSkin. Skinning is explained in the tutorial at (link)"*

If they should be added here, then just drop me a note, and I will create a PR to start filling the 1.1 directory :-)

**Comment by pjcozzi** [comment]
> either appear as "Test cases/models" in a dedicated list

Good idea, let's do this.  Looking forward to the pull request!

**Comment by javagl** [comment]
Done ("accidentally") as discussed in https://github.com/KhronosGroup/glTF-Sample-Models/pull/18#issuecomment-272644365
