### ISSUE TITLE
NormalTangentTest does not work with MikkTSpace (w sign is flipped)

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glTF-Sample-Models#174]
The spec says that if you don't have tangents, you need to compute them, and it recommends MikkTSpace.

However, it is very unclear if NormalTangentTest's normal maps are actually correct, because if you run the geometry through MikkTSpace or any other tangent computation code, I always get w = -1.0. When I render that, I get the same "wrong Y-flip" image mentioned here: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest. If I flip the w sign to 1.0, it works. Is it expected that you have to flip W to make engine-computed tangents work? The spec does not say anything about that.

For reference, here's how I computed tangents before trying MikkTSpace. Looking at MikkTSpace, it's doing the same thing, I get the same W sign results.

```
			vec3 p1 = pos[1] - pos[0];
			vec3 p2 = pos[2] - pos[0];
			vec2 uv1 = uvs[1] - uvs[0];
			vec2 uv2 = uvs[2] - uvs[0];

			float det = 1.0f / (uv1.x * uv2.y - uv1.y * uv2.x);
			vec3 t = det * (p1 * uv2.y - p2 * uv1.y);
			vec3 b = det * (p2 * uv1.x - p1 * uv2.x);
			t = normalize(t);
			b = normalize(b);
```

I have seen three.js do incomprehensible things like just flipping Y (before that it was flipping X ?!?!?), probably to work around issues like this, but I call into question the correctness of these models.

My renderer works fine for NormalTangentMirrorTest (which has TANGENT included), so the shading side of it is correct, i.e. `bitangent = cross(normal, tangent.xyz) * tangent.w`

**Comment by emackey** [comment]
Hi @Themaister, I'm the author of these two models.  I'm not a MikkTSpace expert by any stretch, and I authored these to help gain insight into how these maps work in practice as well as to test the glTF ecosystem for consistency (which was in short supply back when these were new).

The `NormalTangentTest` and `NormalTangentMirrorTest` models both use copies of the same normal map image, from a single bake in Substance Painter using "OpenGL Normals" mode (as opposed to "DirectX" mode that flips the green channel).

The "reference" glTF PBR shader [contains the following code](https://github.com/KhronosGroup/glTF-WebGL-PBR/blob/88eda8c5358efe03128b72b6c5f5f6e5b6d023e1/shaders/pbr-frag.glsl#L111-L139).  This code is intended by the working group to be the standard implementation of the shader calculations:

```
    vec3 pos_dx = dFdx(v_Position);
    vec3 pos_dy = dFdy(v_Position);
    vec3 tex_dx = dFdx(vec3(v_UV, 0.0));
    vec3 tex_dy = dFdy(vec3(v_UV, 0.0));
    vec3 t = (tex_dy.t * pos_dx - tex_dx.t * pos_dy) / (tex_dx.s * tex_dy.t - tex_dy.s * tex_dx.t);

    vec3 ng = normalize(v_Normal);

    t = normalize(t - ng * dot(ng, t));
    vec3 b = normalize(cross(ng, t));
    mat3 tbn = mat3(t, b, ng);

    vec3 n = texture2D(u_NormalSampler, v_UV).rgb;
    n = normalize(tbn * ((2.0 * n - 1.0) * vec3(u_NormalScale, u_NormalScale, 1.0)));
```

The Cesium project and its imported copy of gltf-pipline also [contains the same algorithm](https://github.com/AnalyticalGraphicsInc/cesium/blob/f13dc97c575ecb46e3bfdd12c8f7a64863f6ec93/Source/ThirdParty/GltfPipeline/processPbrMetallicRoughness.js#L482-L491), and gets the same results from the two test models, passing both tests.

Comparing this to your code, it looks quite similar.  When I first looked I thought `det` had the last two terms flipped, but on closer inspection it looks the same to me.  So, I don't know where the problem is, unfortunately.

I did run one more test:  In a temporary folder I re-exported NormalTangentMirrorTest with the "mirrored" parts removed.  Then I loaded the model into gltf-vscode so I could inspect the contents of the tangent accessor.  Without the mirrored parts of the model, all of the exported `w` coordinates read positive `1.0` in the accessor, and the model looks correct.  Remove the `TANGENT` reference from the mesh, and the model still looks correct.  From this I'm fairly certain that existing implementations are computing positive `w` coordinates by default.

Let me know if your investigation makes progress on this.  Thanks!

**Comment by Themaister** [comment]
Right, but there's an issue here, because bi-tangent is not computed, but simply inferred directly from N and T in the shader code. This is equivalent to having W always be 1.0. However, if you try to compute B using the equivalent formulas (using say, MikkTSpace which the spec says you should use), you'd see W = -1.0 on these models.

This is of course a convention issue, but the spec is very vague here. I cannot see any "reference" tangent + bitangent computation.

Question then becomes: Does glTF spec say that W must be 1.0 for engine-computed tangents (only reasonable solution if you want shader-computed tangents), or is W computed based on sign(dot(N, computed_T), computed_B)?

**Comment by emackey** [comment]
The reference implementation does rely on inferred bitangents, and makes no attempt to determine `w`.  I happened to notice that ThreeJS was [recently patched to calculate these](https://github.com/mrdoob/three.js/pull/13716/files).

Doing some testing with NormalTangentMirrorTest, it's easy to remove the reference to the tangents (just delete [line 162](https://github.com/KhronosGroup/glTF-Sample-Models/blob/395358db39e9310bde16aeb65bbea5e32d184d47/2.0/NormalTangentMirrorTest/glTF/NormalTangentMirrorTest.gltf#L162)).  With this line removed, BabylonJS and the newer versions of ThreeJS do calculate the missing tangents and display correctly.  Cesium and the reference shader do not calculate the "mirrored" columns correctly, as they are not calculating `w`, but they do calculate the rest of the geometry correctly (where `w` would have been `1.0`).

The regular parts of this model use positive `1.0`, and the mirrored parts use `-1.0`, but these numbers are of course going not into MikktSpace but rather going into the spec's own formula of `bitangent = cross(normal, tangent.xyz) * tangent.w`.  This formula is more similar to the inferred bitangents than it is to directly calculated bitangents.

Where does your version of the MikktSpace bitangent implementation come from?  Is it possible it came from a left-handed implementation of MikktSpace, or is MikktSpace itself inherently left-handed?

I think it is right for the spec to be such that exported tangents and calculated tangents match, such that I can just remove the `TANGENTS` reference as above and expect the model to fall back on working calculated tangents.  In the spec's current handling of supplied tangents, `1.0` is effectively defined as being right-handed by virtue of being multiplied with a GLSL `cross`.

**Comment by Themaister** [comment]
Right, I see that both ThreeJS and BabylonJS have some kind of "normal scale fudge factor" included, so I suspect the reason it looks correct is that it's using this fudge factor to make it look right.

I had a look at mikktspace and it is doing the same B = cross(N, T) convention that glTF wants, so it looks correct to me.

I also tried computing the tangent in the shader for MirrorTest without TANGENT, which isolates out MikkTSpace issues and I'm getting the same "error" as before that I was getting with MikkTSpace. I tried computing T and B using this:
```
            vec3 dPdx = dFdx(vPosition);
            vec3 dPdy = dFdy(vPosition);
            vec2 dUVdx = dFdx(vUV);
            vec2 dUVdy = dFdy(vUV);
            float det = sign(dUVdx.x * dUVdy.y - dUVdx.y * dUVdy.x);
            mediump vec3 tangent = normalize(det * (dPdx * dUVdy.y - dPdy * dUVdx.y));
            mediump vec3 binormal = normalize(det * (dPdy * dUVdx.x - dPdx * dUVdy.x));
```
I get this:
![shader-computed-bitangent](https://user-images.githubusercontent.com/163683/41254492-eb1325ac-6dc3-11e8-8e6e-4edd583fef1b.png)

Then I tried the plain cross(N, T), and I get the correct result for the two left objects.
![shader-deduced-bitangent](https://user-images.githubusercontent.com/163683/41254526-12453372-6dc4-11e8-96d8-6de55e6ad6f4.png)

I am very confused now :(

**Comment by emackey** [comment]
But in your first sample there, if you simply negate the bitangent that you calculated, it should work correctly, right?  If so I suspect this is just a handedness mixup.

```
            vec3 dPdx = dFdx(vPosition);
            vec3 dPdy = dFdy(vPosition);
            vec2 dUVdx = dFdx(vUV);
            vec2 dUVdy = dFdy(vUV);
            float det = sign(dUVdx.x * dUVdy.y - dUVdx.y * dUVdy.x);
            mediump vec3 tangent = normalize(det * (dPdx * dUVdy.y - dPdy * dUVdx.y));
            mediump vec3 binormal = normalize(-det * (dPdy * dUVdx.x - dPdx * dUVdy.x));
```

**Comment by Themaister** [comment]
Sure, but that is a very arbitrary change that feels like "eh, let's just flip Y". The way these equations are deduced are devoid of any "handed-ness" as far as I can tell. I don't see this "flip" referenced anywhere else.

**Comment by emackey** [comment]
But it's at least safe to say that the bitangent, in the earlier equations, is the negative of the cross of the normal and tangent, yes?  That's why I'm adding a flip there.  Admittedly I'm doing it without a full understanding of MikktSpace, but my addition is at least bringing it into alignment with what `cross` is producing for that vector.  It's entirely possible that official MikktSpace effectively defines bitangents to be the negative of the cross of those vectors for regular (non-mirrored) geometry, in which case the glTF spec could be in error for not explaining that difference.

**Comment by bghgary** [comment]
I'm not an expert on the MikkTSpace code either, though we want to [investigate generating them in BabylonJS](https://github.com/BabylonJS/Babylon.js/issues/3345).

I have been using Unity to export models which uses MikkTSpace to generate the tangent space by default. I tried using the source Blender model for the NormalTangentTest, importing to Unity, export to glTF using my exporter, and manually added back the materials/textures to the glTF. Then, I removed the tangents line in the glTF (you can easily add it back by inserting `"TANGENT": 2,` on line 98. The result:
[NormalTangentTest.zip](https://github.com/KhronosGroup/glTF-Sample-Models/files/2096243/NormalTangentTest.zip)

This behaves just like the sample model as far as I can tell. @Themaister Can you try with this one? I am fairly certain this model has correct MikkTSpace generation as it has been processed by Unity.

**Comment by emackey** [comment]
@Themaister Where does your implementation of the bitangent formula actually come from?

I've learned (the hard way) that normal map "handedness" can be flipped (such that inward bumps go outward and vice-versa) by a number of different means:

* Flip the intensity of the green channel
* Flip the sign on the bitangent (as glTF does with `tangent.w`)
* Flip the winding order in UV space (which does not need to match the winding order in 3D space, and indeed will separate when an artist mirrors some geometry and needs to flip the 3D winding order.  The UV winding order gets flipped as a consequence even though the UV positions have not been mirrored, hence, the sense of their winding order (clock vs counter-clockwise) is now backwards from the original). Changing this winding order causes the bitangents to flip.
* Flip the UV origin from the bottom-left to top-left or vice versa (as this effectively flips every polygon's UV winding order).
* Change from a clockwise-is-front to a counter-clockwise-is-front system in 3D (the conversion for which reverses all the winding orders, including UV winding orders, without moving the UVs, thus flipping all the bitangents).
* Change from a left-handed to right-handed 3D coordinate system (the conversion for which is like a mirror of the geometry and again reverses the winding orders, flipping the bitangents).

I think it's possible that the bitangent formula you've provided above comes from a left-handed instead of right-handed 3D coordinate system, or comes from a lower-left UV origin system that is different from glTF's upper-left UV origin.

Once we get this sorted out, the spec probably does need an update with our conclusions.  I don't think we need to introduce a breaking change, just clarify why our bitangents go the way they go, be it due to our choice of upper-left UV coordinates or such.  Certainly I don't think it's unreasonable that they do go the way they are going, given that `tangent.w` is positive `1.0` when the UV winding order matches the 3D winding order as in this test model.

**Comment by emackey** [comment]
Also (note to self) once this is sorted out, we should update the glTF-WebGL-PBR reference shader to use the bitangent formula instead of the `cross`, so that it can handle mirrored geometry.

**Comment by Themaister** [comment]
@emackey "lower-left UV origin" to me is a misunderstanding. UV space does not have top-left or bottom-left. This distinction only exists in window space. UV (0, 0) maps to the first pixel you put into texture upload functions, that's it.

@bghgary ye, this is kinda awkward, so with the TANGENTS from the glTF, it works. Without them, it doesn't. Maybe Unity flips something and assumes some particular convention?
Anyways, I might just have screwed up, but this is really shaky, since I'm also using MikkTSpace ...

So, the way these formulae are derived is:
- Let the positions of a triangle be p0, p1, p2.
- Let the UV coordinates of a triangle be t0, t1, t2.
- Let Q1 = p1 - p0
- Let Q2 = p2 - p0
- Let UV1 = t1 - t0
- Let UV2 = t2 - t0
- Let T be the tangent
- Let B be the bitangent

We set up two equations for Q1 and Q2, which depend on the tangent/bitangent and deltas of UVs.
- T * UV1.x + B * UV1.y = Q1
- T * UV2.x + B * UV2.y = Q2

If we set this up in matrix form, we get
| T B | * | UV1 UV2 | = | Q1 Q2 |

(note that UV1 is a column here, so is UV2, so a 2x2 matrix):
M =
| UV1.x UV2.x |
| UV1.y UV2.y |

Solve this by taking the inverse:
| T B | = | Q1 Q2 | * | UV1 UV2 |^-1

The inverse of this matrix M is
M^-1 =
| UV2.y -UV2.x |
| -UV1.x UV1.x | / det(M)

det(M) = UV1.x * UV2.y - UV2.x * UV1.y

so, | Q1 Q2 | * M^-1 becomes

T = det(M) * (Q1 * UV2.y - Q2 * UV1.x)
B = det(M) * (Q1 * -UV2.x + Q2 * UV1.x)

This is the only way I have seen B been computed, sans any Y-flipping shenanigans in the past. 

Here's the code in MikkTSpace:
```
		// initial values
		const SVec3 v1 = GetPosition(pContext, piTriListIn[f*3+0]);
		const SVec3 v2 = GetPosition(pContext, piTriListIn[f*3+1]);
		const SVec3 v3 = GetPosition(pContext, piTriListIn[f*3+2]);
		const SVec3 t1 = GetTexCoord(pContext, piTriListIn[f*3+0]);
		const SVec3 t2 = GetTexCoord(pContext, piTriListIn[f*3+1]);
		const SVec3 t3 = GetTexCoord(pContext, piTriListIn[f*3+2]);

		const float t21x = t2.x-t1.x;
		const float t21y = t2.y-t1.y;
		const float t31x = t3.x-t1.x;
		const float t31y = t3.y-t1.y;
		const SVec3 d1 = vsub(v2,v1);
		const SVec3 d2 = vsub(v3,v1);

		const float fSignedAreaSTx2 = t21x*t31y - t21y*t31x;
		//assert(fSignedAreaSTx2!=0);
		SVec3 vOs = vsub(vscale(t31y,d1), vscale(t21y,d2));	// eq 18 <-- Same
		SVec3 vOt = vadd(vscale(-t31x,d1), vscale(t21x,d2)); // eq 19 <-- Same

		pTriInfos[f].iFlag |= (fSignedAreaSTx2>0 ? ORIENT_PRESERVING : 0);

		if ( NotZero(fSignedAreaSTx2) )
		{
			const float fAbsArea = fabsf(fSignedAreaSTx2);
			const float fLenOs = Length(vOs);
			const float fLenOt = Length(vOt);
			const float fS = (pTriInfos[f].iFlag&ORIENT_PRESERVING)==0 ? (-1.0f) : 1.0f; // <-- sign(det(M))
			if ( NotZero(fLenOs) ) pTriInfos[f].vOs = vscale(fS/fLenOs, vOs);
			if ( NotZero(fLenOt) ) pTriInfos[f].vOt = vscale(fS/fLenOt, vOt);

			// evaluate magnitudes prior to normalization of vOs and vOt
			pTriInfos[f].fMagS = fLenOs / fAbsArea;
			pTriInfos[f].fMagT = fLenOt / fAbsArea;

			// if this is a good triangle
			if ( NotZero(pTriInfos[f].fMagS) && NotZero(pTriInfos[f].fMagT))
				pTriInfos[f].iFlag &= (~GROUP_WITH_ANY);
		}
```

**Comment by Themaister** [comment]
Ok, so WebGL Y flipping is a monkey wrench ... Are you supposed to flip textures on load and then invert UV y coordinates to match? That would make the formula work, because negating UV deltas would end up flipping B implicitly ...

Anyways, we just need a clear convention, because as a glTF consumer, there needs to be a one, and only one way to compute these things when an asset is delivered as a glTF. What Blender and friends does is not important as long as the exporter can output to the standard convention which glTF lays down. I'm not saying the formula I pasted is the "only" way to do it. For reference I'm testing this in Vulkan, but I've never had an issue loading textures before from glTF files, so I kinda doubt we were supposed to flip UVs on load ...

Anyways, here's my modified interface to mikktspace:
```
	iface.m_getNumFaces = [](const SMikkTSpaceContext *ctx) -> int {
		const Mesh *m = static_cast<const Mesh *>(ctx->m_pUserData);
		return m->count / 3;
	};

	iface.m_getNumVerticesOfFace = [](const SMikkTSpaceContext *, const int) -> int {
		return 3;
	};

	iface.m_getNormal = [](const SMikkTSpaceContext *ctx, float normals[],
	                       const int iface, const int ivert) {
		int i = iface * 3 + ivert;
		const Mesh *m = static_cast<const Mesh *>(ctx->m_pUserData);
		memcpy(normals, m->attributes.data() + i * m->attribute_stride +
		                m->attribute_layout[ecast(MeshAttribute::Normal)].offset,
		       sizeof(vec3));
	};

	iface.m_getTexCoord = [](const SMikkTSpaceContext *ctx, float normals[],
	                         const int iface, const int ivert) {
		int i = iface * 3 + ivert;
		const Mesh *m = static_cast<const Mesh *>(ctx->m_pUserData);
		memcpy(normals, m->attributes.data() + i * m->attribute_stride +
		                m->attribute_layout[ecast(MeshAttribute::UV)].offset,
		       sizeof(vec2));
	};

	iface.m_getPosition = [](const SMikkTSpaceContext *ctx, float positions[],
	                         const int iface, const int ivert) {
		int i = iface * 3 + ivert;
		const Mesh *m = static_cast<const Mesh *>(ctx->m_pUserData);
		memcpy(positions, m->positions.data() + i * m->position_stride,
		       sizeof(vec3));
	};

	iface.m_setTSpaceBasic = [](const SMikkTSpaceContext *ctx, const float tangent[], const float sign,
	                            const int iface, const int ivert) {
		int i = iface * 3 + ivert;
		Mesh *m = static_cast<Mesh *>(ctx->m_pUserData);
		// Invert the sign because of glTF convention.
		vec4 t(tangent[0], tangent[1], tangent[2], -sign);
		memcpy(m->attributes.data() + i * m->attribute_stride +
		       m->attribute_layout[ecast(MeshAttribute::Tangent)].offset,
		       &t,
		       sizeof(vec4));
	};
```
I tried flipping the sign you get from the library, and the test model in the repo and the one @bghgary posted work as expected. If this is the one true convention for glTF, I'm happy with this, but I'd like to see these formulas in the glTF spec, clearly implementing MikkTSpace as-is not enough.

**Comment by donmccurdy** [comment]
I think I've run into the same thing with https://github.com/KhronosGroup/glTF/issues/1252... starting from the NormalTangentTest or FlightHelmet examples, I am regenerating their tangents with a Rust MikkTSpace implementation I've compiled to WASM. In both examples, the results will match the originals only if the `.w` component of the tangent is inverted (`*= -1`) from the original MikkTSpace output. 

I haven't made any changes to the loader/engine code, but this result is consistent in both three.js and Babylon.js.

[NormalTangentTest-MikkTSpace.zip](https://github.com/KhronosGroup/glTF-Sample-Models/files/5930691/NormalTangentTest-MikkTSpace.zip)

| original | mikkt &times; -1 | mikktspace |
|----|----|----|
| ![Screen Shot 2021-02-04 at 11 00 50 PM](https://user-images.githubusercontent.com/1848368/107000566-ef92b500-673c-11eb-8ad3-d839558bf0fd.png) | ![Screen Shot 2021-02-04 at 11 00 52 PM](https://user-images.githubusercontent.com/1848368/107000575-f3263c00-673c-11eb-8465-6f2a12de4bf3.png) | ![Screen Shot 2021-02-04 at 11 00 53 PM](https://user-images.githubusercontent.com/1848368/107000581-f4576900-673c-11eb-8c75-b06704096df5.png) |

**Comment by emackey** [comment]
@donmccurdy Are you sure you've accounted for glTF's flipY here?  When last I dug into this topic, it appeared that texture image "up" and "down" aren't the same in glTF as they are in a vanilla MikkTSpace implementation.

Also, minor nit, but these test models aren't intended to be viewed off-axis as shown in your screenshots.

**Comment by donmccurdy** [comment]
> Are you sure you've accounted for glTF's flipY here? 

Not at all sure. :) MikkTSpace takes position/normal/uv attributes as input and outputs a tangent attribute, and I'm inputting those attributes directly from a glTF file. MikkTSpace itself does not document any particular convention (https://github.com/mmikk/MikkTSpace/blob/3e895b49d05ea07e4c2133156cfa94369e19e409/mikktspace.h#L72-L78, http://mikktspace.com/) that I can see. If a rewrite of the original attributes is necessary (flipping `uv.y`?) for MikkTSpace to give the correct result it would be great to document that.

**Comment by emackey** [comment]
> MikkTSpace to give the correct result it would be great to document that.

Yes! Once this is finally sorted out, we should document the final word in the glTF spec.

I believe the disconnect stems from the location of the UV origin. UV (0,0) represents the upper-left corner of a glTF texturemap as viewed in an image viewer or browser.  The MikkTSpace page doesn't appear to document what convention is used, but it does mention "The standard is used in Blender 2.57" and we know that Blender uses the opposite orientation, where UV (0,0) is the lower-left of the image as viewed in 2D.

Try flipping (1.0 - uv.y) and see if that gives you the expected result.  It would be great if MikkTSpace itself would document a particular UV coordinate system orientation, but at least we could add this to the glTF spec to make it clear.

**Comment by donmccurdy** [comment]
Ok, thanks — I'll compare `1.0 - uv.y` as well. If it gives the same result as doing `tangent.w *= -1` I'd prefer to do the latter, since I wouldn't need to modify or copy the original attributes, but I'm curious to see if it'll be consistently the same.

**Comment by donmccurdy** [comment]
Following up here — the tangents generated by MikkTSpace after flipping uv.y (`1.0 - uv.y`) are not numerically identical to the output of giving it the original UVs and then flipping the sign (`tangent.w *= -1`), but the two methods were visually identical in the samples I tested (FlightHelmet, NormalTangentTest). By comparison, using the original UVs as input AND directly storing the output tangents was very noticeably different and obviously worse.

Looks like Godot independently came to the same fix (https://github.com/godotengine/godot/pull/23760) already, so I'm going ahead with the `tangent.w *= -1` change in glTF-Transform as well.

**Comment by emackey** [comment]
@donmccurdy Sounds good.  For completeness, if you have time, you might also test what happens in the similarly-named "NormalTangentMirrorTest" if you remove the supplied tangents and recalculate.  This tests what happens when the UV winding order is reversed (in the "mirror" columns).  I think it should also work.

**Comment by donmccurdy** [comment]
Yes, same result there — regenerated tangents look identical to the originals with the `.w *= -1` flip, and incorrect without it.

**Comment by donmccurdy** [comment]
Let's close this issue and continue discussion in https://github.com/KhronosGroup/glTF/issues/2056?
