### ISSUE TITLE
SpecGloss samples

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Sample-Models#181]
It would be nice to have a sample model showing SpecGloss parameters like MetalRoughSpheres.

Also, it would be useful to have an asset with two identical models showing the same visuals with MR and SpecGloss.

**Comment by bghgary** [comment]
> Also, it would be useful to have an asset with two identical models showing the same visuals with MR and SpecGloss.

Are you asking for any models that do this or specifically MetalRoughSpheres? If it's the former, all the SpecGloss models that I put up already do this (e.g. https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoomBox)

**Comment by lexaknyazev** [comment]
I'm asking for an asset that features two instances of the same geometry. E.g. a scene containing two boomboxes that look alike but the first one uses MR while the second uses SpecGloss.

**Comment by emackey** [comment]
> I'm asking for an asset that features two instances of the same geometry [...] that look alike but the first one uses MR while the second uses SpecGloss.

@lexaknyazev This is a (relatively) easy hand-edit to any of the existing specGloss models that contain metalRough fallback textures.  Just copy/paste the mesh and material, and edit one to require spec/gloss and the other to use only MR.  Then use an X translation to separate the two meshes.

For example, here's the edit applied to the WaterBottle model:  [TwoWaterBottles.zip](https://github.com/KhronosGroup/glTF-Sample-Models/files/2181008/TwoWaterBottles.zip)  Extract this into the `2.0\WaterBottle\glTF-pbrSpecularGlossiness` folder.  You may diff it against the original spec/gloss WaterBottle.gltf to see what I did to it.

@donmccurdy I noticed while doing this that ThreeJS treats the spec/gloss 1.0-glossiness very differently from the metal/rough roughness.  I don't think it's a problem with this model as BabylonJS shows a much closer match.  I know there was a recent fix to roughness values in ThreeJS, is it possible the fix was not applied to glossiness values?

![twowaterbottlesinthreejs](https://user-images.githubusercontent.com/1235080/42520657-c3cc2002-8434-11e8-8125-564861c0b043.png)

**Comment by lexaknyazev** [comment]
Looks like this was a useful idea. In such case how about we update all SpecGloss models to the following form?
- an instance with only MR;
- an instance with only SpecGloss;
- an instance with both.

**Comment by donmccurdy** [comment]
> I know there was a recent fix to roughness values in ThreeJS, is it possible the fix was not applied to glossiness values?

That's possible — @takahirox it looks to me like https://github.com/mrdoob/three.js/pull/13501 should generalize, can you think of any reason it would need special handling for glTF spec/gloss?

@emackey just to confirm, what version of three.js are you testing? There was a relevant fix in r89, https://github.com/mrdoob/three.js/issues/12749.

**Comment by emackey** [comment]
@donmccurdy The screenshot is from r92 inside of VSCode.

**Comment by emackey** [comment]
> In such case how about we update all SpecGloss models

I think maybe one or two side-by-side models could be useful for regression testing, but I suspect that upgrading all of them is overkill.

**Comment by SaschaWillems** [comment]
Having at least one model in the repo with both material workflows side-by-side would be a welcome addition.

I have recently added the specular glossiness workflow to my Vulkan PBR implementation and used a modified version of the above water bottle scene to check if both versions render the same way:

![2018-08-04 15_28_22-pbr-vulkan](https://user-images.githubusercontent.com/10283127/43677030-c2304bee-97fb-11e8-921a-e82f0d5bff63.png)

Ideally both workflows give the same result, so I added labels to distinguish between them.

If anyone is interested in using this too, I have uploaded the [modified version over here](http://vulkan.gpuinfo.org/downloads/WaterBottlePbrCompare.7z).
