### ISSUE TITLE
How can i create a box with colored border?

### ISSUE THREAD

**Issue by lukman06** [KhronosGroup/glTF-Sample-Models#189]
Hi i am trying to create a box with colored border how  can i do that ,thanks.

**Comment by emackey** [comment]
What software are you using?  What would a "colored angle" look like?  Is there a screenshot of anything that looks like what you want?

**Comment by lukman06** [comment]
hi thanks for your response i am using node.js i created a cube but not like what i want this is the picture i want 
![rectangle](https://user-images.githubusercontent.com/28634671/44617864-2ae9e380-a863-11e8-964e-292ea1044591.png)

**Comment by javagl** [comment]
This doesn't seem like a property of the *model* (or the material), but rather like a way of *rendering* it - specifically, I think this is referred to as "toon shader" (see e.g. https://threejs.org/examples/#webgl_materials_variations_toon ). But maybe there is a way of emulating this via material properties...

**Comment by emackey** [comment]
I think you should try asking on the relevant forum for whatever software you're using to render the cube.  There's no "outline" property in glTF 2.0, although one could possibly be made with the `KHR_technique_webgl` extension or careful use of texturemapping.  You could also try asking on Stack Overflow, but be aware they will want to see code samples of what you've tried so far.

I'm going to close this since it's not related to the glTF sample models.
