### ISSUE TITLE
BarramundiFish.glb header appears to be garbage

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glTF-Sample-Models#20]

**Comment by javagl** [comment]
I'm also receiving an error message here, when it tries to parse the contained JSON

> Invalid UTF-8 start byte 0xaa

First I thought that it might be related to https://github.com/KhronosGroup/glTF-Sample-Models/pull/9#issuecomment-269063269 , but @cx20 said that the models worked, and during a quick test, Three.js on https://cx20.github.io/gltf-test/ could indeed load the GLB. It will have to be reviewed in more detail.

**Comment by cx20** [comment]
I confirmed the header of BarramundiFish.glb. Since it is a specification that the first 20 bytes are binary, I think that it is not a problem.
![image](https://cloud.githubusercontent.com/assets/1833979/22002324/6bb17ca4-dc8e-11e6-8c77-c4d9f4c715c4.png)
Binary glTF Layout
https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_binary_glTF#binary-gltf-layout

**Comment by mre4ce** [comment]
My apologies. I listed the wrong model. I've opened a new issue for Buggy.glb
