### ISSUE TITLE
Several samples are missing GLB versions

### ISSUE THREAD

**Issue by elalish** [KhronosGroup/glTF-Sample-Models#228]
It would be convenient when pulling this repo and operating on it programatically to have every sample set up the same way. They mostly are, but several of the 2.0 objects are missing the glTF-Binary directory, including Cube, EnvironmentTest, SciFiHelmet, Suzanne, TextureTransformTest, and probably some others as well. I'm happy to run them through gltf-pipeline and submit a PR if that would be helpful.

**Comment by emackey** [comment]
Some of these are intentional, for example the FlightHelmet model is large enough that we were hesitant to contribute multiple versions of it.  But yes, in general it would probably be good if there were better coherence on some of these.

For programmatic access, use [model-index.json](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/model-index.json).

**Comment by DrX3D** [comment]
No comment in 4 years. Many / most of the models in Sample Assets have GLBs. Use the model-index.json in the models directory to determine the various formats and compressions used.

This issue will be closed by 27 November.

**Comment by elalish** [comment]
Fair enough, not a huge deal.
