### ISSUE TITLE
get the Armature node

### ISSUE THREAD

**Issue by CppProgrammer23** [KhronosGroup/glTF-Sample-Models#315]
Hi,

Imagine a model that uses 3 skins and 3 meshes and every  mesh has its own skin attribute. Naturally, I have to get the Armature node, then visit all its children, and every child will point to one mesh and one skin.

my first question is: how get the Armature node ```properly```?

next, how can I visit every mesh and its skin in efficient way (the recursion way seems to be very heavy in term of memory and CPU usage (after profiling)?

**Comment by donmccurdy** [comment]
@CppProgrammer23 each skin may have a direct reference to its "skeleton" node. That's a common ancestor of all joints, and could be considered equivalent to the "armature" you're asking about:

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#skinskeleton

But it is worth noting that the "skeleton" property is not guaranteed to be set, and indeed the joints are not guaranteed to have a common ancestor other than the scene itself. If your application requires a concept of an Armature (not all engines have this concept at all) then you may need to insert a parent above the joints. 

In three.js we process joints in a single pre-pass over all scene nodes, which is fast.

**Comment by CppProgrammer23** [comment]
>  we process joints in a single pre-pass over all scene nodes, which is fast.

can you just explain what do you mean by ```pre-pass over all scene nodes.

I'm trying to make the model from ```Maximo``` Adobe work on my loader. But the FPS drops down and almost the model is blocked. I think because I'm using the ```traverseNode``` recursively.

Any suggestions how to solve this?

**Comment by donmccurdy** [comment]
I'm not sure how to answer this generally – the goal for us is to transform glTF objects into three.js objects. We annotate each node with the type it will take (e.g. THREE.Bone) ...

https://github.com/mrdoob/three.js/blob/e8f0d17e92453bb4dab97c2444ac4dd5439bd92d/examples/jsm/loaders/GLTFLoader.js#L2077-L2129

... and then build the joint hierarchy ...

https://github.com/mrdoob/three.js/blob/e8f0d17e92453bb4dab97c2444ac4dd5439bd92d/examples/jsm/loaders/GLTFLoader.js#L3654

***

If your model has a reasonable number of nodes (<1000?) then iterating over them 1-2 times, recursively or otherwise, should not be a performance problem. If your code is visiting each node many times, say O(n<sup>2</sup>), then I would suggest refactoring your code.

> I'm trying to make the models from Mixamo Adobe work on my loader. But the FPS drops down and almost the model is blocked. I think because I'm using the traverseNode recursively.

Sorry, I don't know what this means, since "making models work" in one engine is different from another, and even the term Armature may mean different things. If you're looking for a good C implementation, perhaps reviewing the code for https://github.com/jkuhlmann/cgltf would be helpful?

**Comment by CppProgrammer23** [comment]
naturally I have, let's say almost 30 in every mesh, and I have 6 meshes.

I have already took a look into that repo, it didn't help much.

but the links you shared are interesting.

Thanks. I will leave this issue open, maybe I will ask something else about the links
