### ISSUE TITLE
FlightHelmet: Implement transmission extension

### ISSUE THREAD

**Issue by mrdoob** [KhronosGroup/glTF-Sample-Models#325]
Currently glass material in the FlightHelmet model renders differently between engines.

<img width="1111" alt="Screen Shot 2021-08-04 at 3 54 39 PM" src="https://user-images.githubusercontent.com/97088/128203569-c8bd845d-800f-45a8-b4b3-06e7ef49f70b.png">

@bghgary  Any chance the model could be updated using the new `transmission` extension?
 
/cc @elalish

**Comment by bghgary** [comment]
I suppose it can be updated in the glTF manually. We don't have the new transmission extension support in the exporters to modify them from source.

Ideally, even if it's not using the transmission extension, it should still render the same. The Babylon.js glTF loader has a flag that makes the transparency as coverage like what the spec says. We don't do it by default because too many people expect it to behave like glass.
