### ISSUE TITLE
It would be great if someone can convert these PBR research models into glTF

### ISSUE THREAD

**Issue by KaminariOS** [KhronosGroup/glTF-Sample-Models#386]
https://benedikt-bitterli.me/resources/

https://github.com/mmp/pbrt-v4-scenes/

By the way, I can perfectly convert FBX models into glTF with Blender, but not Blend models.

**Comment by echadwick-artist** [comment]
These look like they will involve a significant amount of work to convert over. Do you have a preference for which models you want converted? It would help to prioritize assets that might cover test cases not covered by existing glTF sample models.

**Comment by KaminariOS** [comment]
Currently I am not working on rendering. However, imagine that someone is building a PBR glTF renderer and they want to compare their renderer with some other famous renderers like PBRT.

Only with those complex, beautiful and widely-tested scenes can we do the comparison conveniently. For example, this one [Grey and white room](https://benedikt-bitterli.me/resources/images/living-room.png).

**Comment by javagl** [comment]
Given the large number of models and the variety of file formats that they are available in, it could make sense to clarify a few points:

>  "I picked a few of these scenes, cleaned up the geometry, exported it to OBJ and then manually set up PBR materials, lighting and camera" (from the website)

Did this happen in Blender?
If so: What happens when you export these as glTF?

This might be related:

>  I can perfectly convert FBX models into glTF with Blender, but not Blend models.

What does this mean? Is it not possible technically for some reason, or are certain material properties lost?

--

(The goal of these questions is, of course, to avoid (further) _manual_ work for converting the models to glTF. When the required information is already available in a machine-processable form, then it should be possble to automate this process....)

**Comment by KaminariOS** [comment]
You are right. 

It is possible for someone who understands both formats to write a converter. Unfortunately I don't have time to do that.

**Comment by DrX3D** [comment]
Request is too vague or expansive. A more detailed request needs to be made in [Sample Assets](https://github.com/KhronosGroup/glTF-Sample-Assets) for any action to be taken.

If there are no response to this comment by 27 Nov, then this issue will be closed.
