### ISSUE TITLE
a detail...

### ISSUE THREAD

**Issue by Fabrice3D** [KhronosGroup/glTF-Sample-Models#80]
While testing the previous models and the new 2.0 to implement the specs diffs,
I've noticed some empty objects here and there, for instance cesiumMilkTruck as empty object as node 0
line 16.
"nodes": [
        {},
        {

and also as last entry in nodes.
It doesn't really affect my parsing, as the indices seems be sync. 
Just wonder if this is a COLLADA2GLTF bug...

it is also used in scenes
"nodes": [
                6,
                1,
                0
            ]

**Comment by lexaknyazev** [comment]
This is a COLLADA2GLTF issue that was already addressed. 
Sample models will be updated with #76.

**Comment by Fabrice3D** [comment]
ok, btw is there a 2.0 model validator avail somewhere? I've also an exporter and would be handy to test the files other than with my parser that reloads them.

**Comment by lexaknyazev** [comment]
Hosted drag-n-drop version supports 2.0:
http://github.khronos.org/glTF-Validator/

**Comment by Fabrice3D** [comment]
Awesome! Thank you lexaknyazev

**Comment by javagl** [comment]
Just to have the references here: The issue was reported (for a specific case) here https://github.com/KhronosGroup/glTF-Sample-Models/issues/52 , and more generally, referring to COLLADA2GLTF (including a fix) here https://github.com/KhronosGroup/COLLADA2GLTF/issues/44 

So I guess this one could be closed?
